import { redirect } from "next/navigation";
// FIXME: import { auth } from "../../../../auth";
import { auth } from "../../../../auth";
import Navbar from "./components/Navbar";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "@/components/ui/toaster";
import "../../globals.css"
import BreadcrumbDashboard from "./components/BreadcrumbDashboard";
import { Metadata } from "next";
import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();

  if (!session) {
    return redirect("/auth/login");
  }

  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <SessionProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem={true}
            disableTransitionOnChange
          >
            <Navbar />
            <main className="w-full flex flex-col justify-start items-center pt-8 bg-white dark:bg-black transition">
              <div className="max-w-[50rem] px-8 w-full">
                <div className="flex mb-4 mt-16 flex-row items-start">
                  <BreadcrumbDashboard />
                </div>
                {children}
                <Toaster />
              </div>
            </main>
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
